# Generated by Django 2.0.6 on 2021-03-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
                ('salt', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
