# Generated by Django 2.0.6 on 2021-03-16 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'depart_info',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('age', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=1)),
                ('birthday', models.DateField()),
                ('head_pic', models.ImageField(null=True, upload_to='pic')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Department')),
            ],
            options={
                'db_table': 'employee_info',
            },
        ),
    ]
